### ISSUE TITLE
Can't login (always "Error: Invalid credentials")

### ISSUE THREAD

**Issue by hisxo** [lmammino/sample-jwt-webapp#1]
Hello,

First, thanks for this project which is cool to learn and understand more how about JWT work. I tried this app "by default" and when I try to connect with default logins, the app always answer "Error: Invalid credentials" do you know why? Do I need to do something before to start app?

Thanks :)

**Comment by lmammino** [comment]
Hello @BlackPearl01 and thanks for trying this project :)

the default config is described in the [README](https://github.com/lmammino/sample-jwt-webapp#configuration). Default username is `luciano` and  password `mariobros`. Make sure you type them correctly without extra spaces. if you prefer you can change those as follows (in unix or mac):

```bash
USERNAME=yourusername PASSWORD=somepassword SECRET=somesecret npm start
```

**Comment by lmammino** [comment]
Let me know if this helps you or if you still have problems logging in

**Comment by hisxo** [comment]
Hello !

Thanks, it's ok for now! :)

Regards,
